### ISSUE TITLE
Update docs on the GitHub page

### ISSUE THREAD

**Issue by vkabadzhova** [QuantumSavory/QuantumClifford.jl#188]
It seems that the docs available on the GitHub page are an older version of the documentation available in the source. This can be seen below:

For example, in the picture below there's a typo stating that the `to_cpu()` function copies the memory content of the object to the **GPU** instead of copying it to the **CPU**.
![qcliff-docs-screenshot](https://github.com/QuantumSavory/QuantumClifford.jl/assets/36995171/449a825f-f352-4cb5-8960-91ee8de865ce)

However, this problem seems to be fixed with #180 from @Shayan-P (see the diff file [here](https://github.com/QuantumSavory/QuantumClifford.jl/pull/180/files#diff-c071e682cd00dca12caf5d7404e4d3c49ac55089bbd7f68899b473db24a7f131))

**Comment by Krastanov** [comment]
Thanks, Violeta! I believe the fix is present in the dev version of the docs https://quantumsavory.github.io/QuantumClifford.jl/dev/API/

When 0.8.17 is released, the fix will be present in the stable version of the docs as well. Versions can be selected from the bottom left menu.

Do not hesitate to point out any other inconsistencies you find (or submit pull requests).

I am closing this for now as it is already fixed in the repo.
