### ISSUE TITLE
`iscss` function that announces a code type is a CSS code

### ISSUE THREAD

**Issue by Krastanov** [QuantumSavory/QuantumClifford.jl#222]
It should simply have methods defined for each code type, it should not run checks of the tableaux itself. It should be hooked into `parity_checks_x/z` for better error messages.

**Comment by Fe-r-oz** [comment]
@Krastanov  By each code type, do you mean the codes that are in the codes section?

Also, it seems that you want it to be implemented in ECC.jl as there is where parity_checks_x/z are implemented?

If we don't want to include checks of the Stabilizer, then do we need to separate the quantum codes into classical variants and then determine if every code word in suppose C2 is in C1. Because that's the [standard definition ](https://en.wikipedia.org/wiki/CSS_code) of whether a code is CSS or not?

**Comment by Fe-r-oz** [comment]
Thanks. For example, There is a` parity_check_xz `in the `Toric` case, right?

**Comment by Krastanov** [comment]
yes

**Comment by Krastanov** [comment]
done in #241
